const prefix = `ERROR`

export default {
    LOGIN_FAILURE: `${prefix}:LOGIN_FAILURE`,
    LOGIN_CHECK_FAILURE: `${prefix}:LOGIN_FAILURE`,
    JOIN_ROOM_FAILURE: `${prefix}:JOIN_ROOM_FAILURE`,
    LEAVE_ROOM_FAILURE: `${prefix}:LEAVE_ROOM_FAILURE`,
    REGISTRATION_FAILURE: `${prefix}:REGISTRATION_FAILURE`,
    FETCH_ROOM_MESSAGES_FAILURE: `${prefix}:FETCH_ROOM_MESSAGES_FAILURE`,
    SEND_FAILURE: `${prefix}:SEND_FAILURE`,
    RECIVE_FAILURE: `${prefix}:RECIVE_FAILURE`,
    NICKNAME_FAILURE: `${prefix}:NICKNAME_FAILURE`,
    CLEAN: `${prefix}:CLEAN`
}