const prefix = `LISTENER`

export default {
    FETCH_MESSAGES_REQUEST: `${prefix}:FETCH_MESSAGES_REQUEST`,
    SEND_MESSAGE_REQUEST: `${prefix}:SEND_MESSAGE_REQUEST`,
    RECIVE_MESSAGE_REQUEST: `${prefix}:RECIVE_MESSAGE_REQUEST`,
    CHANGE_NICKNAME_REQUEST: `${prefix}:CHANGE_NICKNAME_REQUEST`
}