const prefix = `LISTENER`

export default {
    USER_LOGINCHECK_REQUEST: `${prefix}:USER_LOGINCHECK_REQUEST`,
    USER_LOGOUT_REQUEST: `${prefix}:USER_LOGOUT_REQUEST`,
    USER_LOGIN_REQUEST: `${prefix}:USER_LOGIN_REQUEST`,
    USER_REGISTRATION_REQUEST: `${prefix}:USER_REGISTRATION_REQUEST`,
    FETCH_ROOM_MESSAGES_REQUEST: `${prefix}:FETCH_ROOM_MESSAGES_REQUEST`,
    JOIN_ROOM_REQUEST: `${prefix}:JOIN_ROOM_REQUEST`,
    LEAVE_ROOM_REQUEST: `${prefix}:LEAVE_ROOM_REQUEST`,
    SEND_MESSAGE_REQUEST: `${prefix}:SEND_MESSAGE_REQUEST`,
    RECIVE_MESSAGE_REQUEST: `${prefix}:RECIVE_MESSAGE_REQUEST`,
    CHANGE_NICKNAME_REQUEST: `${prefix}:CHANGE_NICKNAME_REQUEST`,
    CONNECT_REQUEST: `${prefix}:CONNECT_REQUEST`,
    CONNECT_SUCCESS: `${prefix}:CONNECT_SUCCESS`,
    LISTENER_CANCEL: `${prefix}:LISTENER_CANCEL`,
    DISCONNECT_SUCCESS: `${prefix}:DISCONNECT_SUCCESS`,
    USER_LOGIN_SUCCESS: `${prefix}:USER_LOGIN_SUCCESS`,
    USER_REGISTRATION_COMPLETE: `${prefix}:USER_REGISTRATION_COMPLETE`,
}